### ISSUE TITLE
Broken links on docusaurus build

### ISSUE THREAD

**Issue by thomastaylor312** [bytecodealliance/wasi.dev#27]
When running a docusaurus build, it finds a bunch of broken links on main

```
Error: Unable to build website for locale en.
    at tryToBuildLocale (/private/tmp/wasi.dev/node_modules/@docusaurus/core/lib/commands/build.js:55:19)
    at async mapAsyncSequential (/private/tmp/wasi.dev/node_modules/@docusaurus/utils/lib/jsUtils.js:44:24)
    at async Command.build (/private/tmp/wasi.dev/node_modules/@docusaurus/core/lib/commands/build.js:82:21) {
  [cause]: Error: Docusaurus found broken links!

  Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
  Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

  It looks like some of the broken links we found appear in many pages of your site.
  Maybe those broken links appear on all pages through your site layout?
  We recommend that you check your theme configuration for such links (particularly, theme navbar and footer).
  Frequent broken links are linking to:
  - /docs/intro

  Exhaustive list of all broken links found:
  - Broken link on source page path = /404.html:
     -> linking to /docs/intro
  - Broken link on source page path = /markdown-page:
     -> linking to /docs/intro
  - Broken link on source page path = /contribute:
     -> linking to /docs/intro
  - Broken link on source page path = /interfaces:
     -> linking to /docs/intro
  - Broken link on source page path = /resources:
     -> linking to /docs/intro
  - Broken link on source page path = /:
     -> linking to /docs/intro

      at throwError (/private/tmp/wasi.dev/node_modules/@docusaurus/logger/lib/index.js:79:11)
      at reportBrokenLinks (/private/tmp/wasi.dev/node_modules/@docusaurus/core/lib/server/brokenLinks.js:242:47)
      at handleBrokenLinks (/private/tmp/wasi.dev/node_modules/@docusaurus/core/lib/server/brokenLinks.js:274:5)
      at buildLocale (/private/tmp/wasi.dev/node_modules/@docusaurus/core/lib/commands/build.js:192:47)
      at async tryToBuildLocale (/private/tmp/wasi.dev/node_modules/@docusaurus/core/lib/commands/build.js:46:20)
      at async mapAsyncSequential (/private/tmp/wasi.dev/node_modules/@docusaurus/utils/lib/jsUtils.js:44:24)
      at async Command.build (/private/tmp/wasi.dev/node_modules/@docusaurus/core/lib/commands/build.js:82:21)
}

[INFO] Docusaurus version: 3.1.1
Node version: v20.12.2
```

**Comment by ericgregory** [comment]
This was resolved by adjusting the footer "Introduction" link to `/` in #31 and #32.
